name: Streamlit Tests with Poetry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

 
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"  

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies with Poetry
        working-directory: etude_app_cuisine
        run: |
          poetry install  # Install all dependencies including dev tools
          poetry show     # Optional: List installed dependencies
          poetry run python --version

      - name: Run Linting with Flake8
        working-directory: etude_app_cuisine
        continue-on-error: true
        run: poetry run flake8 src tests --max-line-length=120

      - name: Generate Data
        working-directory: etude_app_cuisine/src
        run: poetry run python LoadData.py  

      - name: List Generated Data Files
        working-directory: etude_app_cuisine/src
        run: ls -l data_loaded
        
      - name: Run Tests
        working-directory: etude_app_cuisine
        run: poetry run pytest --maxfail=5 --disable-warnings
