name: Streamlit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: etude_app_cuisine/src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Clear pip cache
        run: pip cache purge
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r etude_app_cuisine/requirements.txt
          pip show gdown
      - name: Ensure data_loaded directory exists
        run: |
          if [ ! -d etude_app_cuisine/src/data_loaded ]; then
            mkdir etude_app_cuisine/src/data_loaded
          fi
      - name: Generate data
        run: |
          python etude_app_cuisine/src/LoadData.py
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: etude_app_cuisine/src/app_v3.py
